[package]
name = "nannou_dots"
version = "0.1.0"
authors = ["Thomas Belahi <tbelahi@ehda.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

nannou = "0.16"
palette = "*" 
